# Generated by Django 2.1.5 on 2021-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Is_Patient',
            field=models.BooleanField(default=True),
        ),
    ]
