# Generated by Django 2.1.5 on 2021-06-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Is_Patient',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_patient',
            field=models.TextField(blank=True, null=True),
        ),
    ]
